"""General MIDI."""


PROGRAM_MAP = {
    "gm_acoustic_grand_piano": 0,
    "gm_bright_acoustic_piano": 1,
    "gm_electric_grand_piano": 2,
    "gm_honky_tonk_piano": 3,
    "gm_electric_piano_1": 4,
    "gm_electric_piano_2": 5,
    "gm_harpsichord": 6,
    "gm_clavi": 7,
    "gm_celesta": 8,
    "gm_glockenspiel": 9,
    "gm_music_box": 10,
    "gm_vibraphone": 11,
    "gm_marimba": 12,
    "gm_xylophone": 13,
    "gm_tubular_bells": 14,
    "gm_dulcimer": 15,
    "gm_drawbar_organ": 16,
    "gm_percussive_organ": 17,
    "gm_rock_organ": 18,
    "gm_church_organ": 19,
    "gm_reed_organ": 20,
    "gm_accordion": 21,
    "gm_harmonica": 22,
    "gm_tango_accordion": 23,
    "gm_acoustic_guitar_nylon": 24,
    "gm_acoustic_guitar_steel": 25,
    "gm_electric_guitar_jazz": 26,
    "gm_electric_guitar_clean": 27,
    "gm_electric_guitar_muted": 28,
    "gm_overdriven_guitar": 29,
    "gm_distortion_guitar": 30,
    "gm_guitar_harmonics": 31,
    "gm_acoustic_bass": 32,
    "gm_electric_bass_finger": 33,
    "gm_electric_bass_pick": 34,
    "gm_fretless_bass": 35,
    "gm_slap_bass_1": 36,
    "gm_slap_bass_2": 37,
    "gm_synth_bass_1": 38,
    "gm_synth_bass_2": 39,
    "gm_violin": 40,
    "gm_viola": 41,
    "gm_cello": 42,
    "gm_contrabass": 43,
    "gm_tremolo_strings": 44,
    "gm_pizzicato_strings": 45,
    "gm_orchestral_harp": 46,
    "gm_timpani": 47,
    "gm_string_ensemble_1": 48,
    "gm_string_ensemble_2": 49,
    "gm_synthstrings_1": 50,
    "gm_synthstrings_2": 51,
    "gm_choir_aahs": 52,
    "gm_voice_oohs": 53,
    "gm_synth_voice": 54,
    "gm_orchestra_hit": 55,
    "gm_trumpet": 56,
    "gm_trombone": 57,
    "gm_tuba": 58,
    "gm_muted_trumpet": 59,
    "gm_french_horn": 60,
    "gm_brass_section": 61,
    "gm_synthbrass_1": 62,
    "gm_synthbrass_2": 63,
    "gm_soprano_sax": 64,
    "gm_alto_sax": 65,
    "gm_tenor_sax": 66,
    "gm_baritone_sax": 67,
    "gm_oboe": 68,
    "gm_english_horn": 69,
    "gm_bassoon": 70,
    "gm_clarinet": 71,
    "gm_piccolo": 72,
    "gm_flute": 73,
    "gm_recorder": 74,
    "gm_pan_flute": 75,
    "gm_blown_bottle": 76,
    "gm_shakuhachi": 77,
    "gm_whistle": 78,
    "gm_ocarina": 79,
    "gm_lead_1_square": 80,
    "gm_lead_2_sawtooth": 81,
    "gm_lead_3_calliope": 82,
    "gm_lead_4_chiff": 83,
    "gm_lead_5_charang": 84,
    "gm_lead_6_voice": 85,
    "gm_lead_7_fifths": 86,
    "gm_lead_8_bass_+_lead": 87,
    "gm_pad_1_new_age": 88,
    "gm_pad_2_warm": 89,
    "gm_pad_3_polysynth": 90,
    "gm_pad_4_choir": 91,
    "gm_pad_5_bowed": 92,
    "gm_pad_6_metallic": 93,
    "gm_pad_7_halo": 94,
    "gm_pad_8_sweep": 95,
    "gm_fx_1_rain": 96,
    "gm_fx_2_soundtrack": 97,
    "gm_fx_3_crystal": 98,
    "gm_fx_4_atmosphere": 99,
    "gm_fx_5_brightness": 100,
    "gm_fx_6_goblins": 101,
    "gm_fx_7_echoes": 102,
    "gm_fx_8_sci_fi": 103,
    "gm_sitar": 104,
    "gm_banjo": 105,
    "gm_shamisen": 106,
    "gm_koto": 107,
    "gm_kalimba": 108,
    "gm_bag_pipe": 109,
    "gm_fiddle": 110,
    "gm_shanai": 111,
    "gm_tinkle_bell": 112,
    "gm_agogo": 113,
    "gm_steel_drums": 114,
    "gm_woodblock": 115,
    "gm_taiko_drum": 116,
    "gm_melodic_tom": 117,
    "gm_synth_drum": 118,
    "gm_reverse_cymbal": 119,
    "gm_guitar_fret_noise": 120,
    "gm_breath_noise": 121,
    "gm_seashore": 122,
    "gm_bird_tweet": 123,
    "gm_telephone_ring": 124,
    "gm_helicopter": 125,
    "gm_applause": 126,
    "gm_gunshot": 127,
}


PERCUSSION_CHANNEL = 9


_PERCUSSION_MAP = {
    # Bass drums
    35: ["abd", "ABD", "acoustic_bass_drum"],
    36: ["bd",  "BD",  "bass_drum_1"],
    # Snares
    40: ["esn", "ESN", "electric_snare"],
    38: ["sn",  "SN",  "acoustic_snare"],
    # Sticks/claps
    37: ["st",  "ST",  "side_stick"],
    39: ["cp",  "CP",  "hand_clap"],
    # Toms
    41: ["lft", "LFT", "low_floor_tom"],
    43: ["hft", "HFT", "high_floor_tom"],
    45: ["lt",  "LT",  "low_tom"],
    47: ["lmt", "LMT", "low_mid_tom"],
    48: ["hmt", "HMT", "hi_mid_tom"],
    50: ["ht",  "HT",  "high_tom"],
    # Hats
    42: ["hh",  "HH",  "closed_hi_hat"],
    44: ["ph",  "PH",  "pedal_hi_hat"],
    46: ["oh",  "OH",  "open_hi_hat"],
    # Cymbals
    49: ["cr",  "CR",  "crash_cymbal_1"],
    57: ["cr2", "CR2", "crash_cymbal_2"],
    51: ["rc",  "RC",  "ride_cymbal_1"],
    59: ["rc2", "RC2", "ride_cymbal_2"],
    52: ["chc", "CHC", "chinese_cymbal"],
    55: ["spc", "SPC", "splash_cymbal"],
    # Everything else
    53: ["bel", "BEL", "ride_bell"],
    54: ["tam", "TAM", "tambourine"],
    56: ["cow", "COW", "cowbell"],
    58: ["vbs", "VBS", "vibraslap"],
    60: ["hb",  "HB",  "hi_bongo"],
    61: ["lb",  "LB",  "low_bongo"],
    62: ["mhc", "MHC", "mute_hi_conga"],
    63: ["ohc", "OHC", "open_hi_conga"],
    64: ["lc",  "LC",  "low_conga"],
    65: ["hti", "HTI", "high_timbale"],
    66: ["lti", "LTI", "low_timbale"],
    67: ["hag", "HAG", "high_agogo"],
    68: ["lag", "LAG", "low_agogo"],
    69: ["cab", "CAB", "cabasa"],
    70: ["mar", "MAR", "maracas"],
    71: ["swh", "SWH", "short_whistle"],
    72: ["lwh", "LWH", "long_whistle"],
    73: ["sgu", "SGU", "short_guiro"],
    74: ["lgu", "LGU", "long_guiro"],
    75: ["cla", "CLA", "claves"],
    76: ["hwb", "HWB", "hi_wood_block"],
    77: ["lwb", "LWB", "low_wood_block"],
    78: ["mcu", "MCU", "mute_cuica"],
    79: ["ocu", "OCU", "open_cuica"],
    80: ["mtr", "MTR", "mute_triangle"],
    81: ["otr", "OTR", "open_triangle"],
}

PERCUSSION_MAP = {
    name: pitch
    for pitch, names in _PERCUSSION_MAP.items()
    for name in names
}

